apiVersion: batch/v1
kind: Job
metadata:
  name: initialize
  labels:
    runboat/job-kind: initialize
spec:
  template:
    metadata:
      labels:
        runboat/job-kind: initialize
    spec:
      enableServiceLinks: false
      initContainers:
        - name: build-image
          image: docker:dind
          securityContext:
            privileged: true
          args: ["sh", "/runboat/runboat-build-image.sh"]
          envFrom:
            - secretRef:
                name: secretenv
            - configMapRef:
                name: buildenv
          volumeMounts:
            - name: runboat-scripts
              mountPath: /runboat
      containers:
        - name: initialize
          image: odoo
          volumeMounts:
            - name: runboat-scripts
              mountPath: /runboat
            - name: data
              mountPath: /odoo/data
          envFrom:
            - secretRef:
                name: secretenv
            - configMapRef:
                name: odooenv
          args: ["/runboat/runboat-initialize.sh"]
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: runboat-scripts
          configMap:
            name: runboat-scripts
        - name: data
          persistentVolumeClaim:
            claimName: data
      restartPolicy: Never
  completions: 1
  backoffLimit: 0
  activeDeadlineSeconds: 7200
