apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
