name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project
        run: |
          pip install -U "pip>=21.3.1"
          pip install -e .[test,mypy] -c requirements.txt -c requirements-test.txt -c requirements-mypy.txt
      - name: Run tests
        run: pytest -v --cov --cov-report=xml ./tests
      - name: Run mypy
        run: mypy ./src/runboat ./tests
      - uses: codecov/codecov-action@v1
  build-image:
    runs-on: ubuntu-latest
    needs:
      - test
    if: ${{ github.repository_owner == 'onesteinbv' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          tags: |
            ghcr.io/${{ github.repository }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:latest
          cache-to: type=inline
          push: true
